
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/api_spring
        username: root
        password: Nanana12*
#        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true


