
spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/api_spring
        url: jdbc:mysql://mysql_container/api_spring
        username: root
        password: Nanana12*
#        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
server:
    port: 8080


