package com.example.ApiRest.Model.Enum;

public enum StudentDegree {

    COMPUTER_SYSTEM_ENGINEERING,
    ENVIRONMENTAL_ENGINEERING,
    BUSINESS_MANAGEMENT_ENGINEERING,
    INDUSTRIAL_ENGINEERING

}
